image: bitsensor/nvm

before_script:
  - source ~/.bashrc
  - nvm install "$(cat .node-version)"
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
  - npm install

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - lib/
      - node_modules/

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - lib/
      - node_modules/

lint:
  stage: test
  script:
    - eslint .
  allow_failure: true

deploy:
  stage: deploy
  script:
    - scripts/update-authors.sh
    - npm publish --access public
  only:
    - master
  artifacts:
      paths:
        - lib/
