stages:
  - build
  - test
  - deploy
  - mirror

build:
  image: node
  stage: build
  script:
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm install
    - npm run build
  artifacts:
    paths:
      - lib/
      - node_modules/

test:
  image: node
  stage: test
  script:
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm install
    - npm test
  artifacts:
    paths:
      - lib/
      - node_modules/

lint:
  image: node
  stage: test
  script:
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm install
    - ./node_modules/.bin/eslint .
  allow_failure: true

deploy:npm:
  image: node
  stage: deploy
  script:
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm install
    - scripts/update-authors.sh
    - npm publish --access public
  only:
    - tags
  artifacts:
      paths:
        - lib/

deploy:docker:
  tags:
    - docker
  stage: deploy
  script:
    - docker info
    - docker login -u $BITSENSOR_USERNAME -p $BITSENSOR_PASSWORD artifacts.bitsensor.io:1443
    - docker build -t elastalert .
    - docker tag elastalert artifacts.bitsensor.io:1443/elastalert:latest
    - docker tag elastalert artifacts.bitsensor.io:1443/elastalert:$(git describe --abbrev=0)
    - docker push artifacts.bitsensor.io:1443/elastalert:latest
    - docker push artifacts.bitsensor.io:1443/elastalert:$(git describe --abbrev=0)
  artifacts:
    paths:
      - lib/
      - node_modules/
  only:
    - tags

deploy:docker:snapshot:
  tags:
    - docker
  stage: deploy
  script:
    - docker info
    - docker login -u $BITSENSOR_USERNAME -p $BITSENSOR_PASSWORD artifacts.bitsensor.io:1443
    - docker build -t elastalert .
    - docker tag elastalert artifacts.bitsensor.io:1443/elastalert:snapshot
    - docker push artifacts.bitsensor.io:1443/elastalert:snapshot
  artifacts:
    paths:
      - lib/
      - node_modules/
  only:
    - develop

mirror:github:
  image: debian
  stage: mirror
  script:
    - apt-get update && apt-get install -y git
    - git clone --mirror https://git.bitsensor.io/back-end/elastalert.git mirror-github
    - cd mirror-github
    - git remote add github https://$MIRROR_GITHUB_USER:$MIRROR_GITHUB_PASSWORD@$MIRROR_GITHUB_URL
    - git push -u github -q --mirror
  when: always
