stages:
  - build
  - test
  - deploy
  - mirror

cache:
  key: elastalert
  paths:
    - node_modules/
  policy: pull

build:
  image: node:slim
  stage: build
  cache:
    key: elastalert
    paths:
      - node_modules/
    policy: push
  script:
    - npm i -q
    - npm run build

test:
  image: node:slim
  stage: test
  script:
    - npm i -q
    - npm test

lint:
  image: node:slim
  allow_failure: true
  stage: test
  script:
    - npm i -q
    - ./node_modules/.bin/eslint .

deploy:npm:
  image: node:slim
  stage: deploy
  script:
    - scripts/update-authors.sh
    - npm publish --access public
  only:
    - tags

deploy:docker:
  stage: deploy
  script:
    - docker info
    - docker login -u $BITSENSOR_USERNAME -p $BITSENSOR_PASSWORD artifacts.bitsensor.io:1443
    - docker build -t elastalert .
    - docker tag elastalert artifacts.bitsensor.io:1443/elastalert:latest
    - docker tag elastalert artifacts.bitsensor.io:1443/elastalert:$(git describe --abbrev=0)
    - docker push artifacts.bitsensor.io:1443/elastalert:latest
    - docker push artifacts.bitsensor.io:1443/elastalert:$(git describe --abbrev=0)
  only:
    - tags
  tags:
    - docker

deploy:docker:snapshot:
  stage: deploy
  script:
    - docker info
    - docker login -u $BITSENSOR_USERNAME -p $BITSENSOR_PASSWORD artifacts.bitsensor.io:1443
    - docker build -t elastalert .
    - docker tag elastalert artifacts.bitsensor.io:1443/elastalert:snapshot
    - docker push artifacts.bitsensor.io:1443/elastalert:snapshot
  only:
    - develop
  tags:
    - docker

mirror:github:
  stage: mirror
  script:
    - git clone --mirror https://git.bitsensor.io/back-end/elastalert.git mirror-github
    - cd mirror-github
    - git remote add github https://$MIRROR_GITHUB_USER:$MIRROR_GITHUB_PASSWORD@$MIRROR_GITHUB_URL
    - git push -u github -q --mirror
  when: always
